spring:
  artemis:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
#    broker-url: tcp://211.236.39.250:46161
#    user: onelbs
#    password: onelbs
    threadPool: 10

jms:
  queue:
    send:
      event: ip-request
    recv:
      evnet: ip-response

server:
  forward-headers-strategy: native